### PR TITLE
fix(Popup): do not throw if `context` & `trigger` are missing

### LINKED ISSUE #3896: Popup: Context menu Uncaught (in promise) TypeError
### Steps
We migrated from to version 0.85.0 to 0.88.2 and our context menu stopped working.
Here is how the context menu is implemented: https://codesandbox.io/s/semantic-ui-react-f1k0i

In order to reproduce, please switch the semantic-ui version from 0.85.0 to 0.88.2

### Expected Result
Open a pop-up window when doing right-click on the table header

### Actual Result
JavaScript error
`Uncaught (in promise) TypeError: Cannot read property 'left' of undefined`

### Version
0.88.2

### Testcase
https://codesandbox.io/s/semantic-ui-react-f1k0i

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #3896.

This PR adds an example with context menu usage and fixes an issue when `trigger` and `context` are not defined to prevent throwing errors.

### CODE REVIEW

File: src/modules/Popup/lib/createReferenceProxy.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ class ReferenceProxy {
   }
 
   getBoundingClientRect() {
-    return _.invoke(this.ref.current, 'getBoundingClientRect', {})
+    return _.invoke(this.ref.current, 'getBoundingClientRect') || {}
```
Comment (layershifter) [inline src/modules/Popup/lib/createReferenceProxy.js:10]: This is my the most common mistake with Lodash: `_.invoke()` as 3rd parameter has a call argument, not a default value 🤦
