### PR TITLE
fix(Form): fix handling of `action` prop

### LINKED ISSUE #1882: Form: action prop is missing in generated markup
### Steps

Create a Form:
```jsx
<Form method="POST" action="/convert"  encType="multipart/form-data" />
```

### Expected Result

Get a form with action `/convert`.

### Actual Result

the property action is missing

### Version

0.71.1

### Testcase

https://codepen.io/anon/pen/PjMpex

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1882.

### CODE REVIEW

File: test/specs/collections/Form/Form-test.js [hunk 1]
```diff
@@ -31,7 +32,9 @@ describe('Form', () => {
   common.hasUIClassName(Form)
   common.rendersChildren(Form)
 
-  common.implementsWidthProp(Form, _.without(SUI.SIZES, 'medium'), { propKey: 'widths' })
+  common.implementsWidthProp(Form, [], {
+    propKey: 'widths',
+  })
```
Comment (layershifter) [inline test/specs/collections/Form/Form-test.js:37]: Also fixed a test that produced propTypes' warning, `Form` can accept only `equal` width.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.2`
