### PR TITLE
fix(Responsive): fix types in typings

### LINKED ISSUE #2608: Responsive: wrong type of `width` in ResponsiveOnUpdateData
In Responsive.d.ts, the type of the width property in the ResponsiveOnUpdateData interface is "string" but this should be "number".

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2608.

### CODE REVIEW

File: src/addons/Responsive/Responsive.d.ts [hunk 1]
```diff
@@ -28,12 +28,12 @@ export interface ResponsiveProps {
...
 
 export interface ResponsiveOnUpdateData extends ResponsiveProps {
-  width: string;
+  width: number;
 }
 
 export interface ResponsiveWidthShorthand {
-  minWidth: number;
-  maxWidth?: number;
+  minWidth?: number | string;
```
Comment (layershifter) [inline src/addons/Responsive/Responsive.d.ts:35]: `minWidth` is actually optional

File: src/addons/Responsive/Responsive.d.ts [hunk 2]
```diff
@@ -28,12 +28,12 @@ export interface ResponsiveProps {
...
+  maxWidth?: number | string;
```
Comment (layershifter) [inline src/addons/Responsive/Responsive.d.ts:36]: `minWidth` and `maxWidth` can be strings, see props definitions

File: src/addons/Responsive/Responsive.d.ts (hunk 1 above)
Comment (MJLHThomassen-Eurocom) [reply src/addons/Responsive/Responsive.d.ts:35]: This is a potentially breaking change (everyone who expects minWidth to be there and has coded against it will now potentially run into linter errors stating that minWidth is optional and should change their code to check for this).

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.79.0`.
