### PR TITLE
fix(Button): update handling of floated prop

### LINKED ISSUE #1488: Button: floated doesn't work for Labeled Button
**Steps to Reproduce**
1. Add property "floated" with value "right" to a labeled button.

```
    <Button
      icon='fork'
      label={{ as: 'a', basic: true, content: '2,048' }}
      labelPosition='left'
      floated='right'
    />
```

**Expected**
The Button should be at the right side of the container.

**Result**
The Button doesn't move to the right side.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1488.

`floated` class must be on wrapper if we have `Label` element, this PR update handling of this.

### CODE REVIEW

File: src/elements/Button/Button.js [hunk 1]
```diff
@@ -229,18 +231,23 @@ class Button extends Component {
...
+    const wrapperClasses = cx(
+      useKeyOnly(disabled, 'disabled'),
       useValueAndKey(floated, 'floated'),
     )
-    const wrapperClasses = cx(useKeyOnly(disabled, 'disabled'))
+
     const rest = getUnhandledProps(Button, this.props)
-    const ElementType = getElementType(Button, this.props, () => {
-      if (!_.isNil(label) || !_.isNil(attached)) return 'div'
-    })
```
Comment (layershifter) [inline src/elements/Button/Button.js:238]: I've moved this inline function to method, so it will not be created on each render.

File: test/specs/elements/Button/Button-test.js [hunk 2]
```diff
@@ -109,6 +109,11 @@ describe('Button', () => {
       wrapper.find('Label').should.not.have.className('disabled')
       wrapper.find('button').should.not.have.className('disabled')
     })
+    it('contains children without floated class when floated attribute is set', () => {
```
Comment (levithomason) [inline test/specs/elements/Button/Button-test.js:114]: Would prefer we assert the expected location of the floated class in this test as well. It currently asserts where the className should _not_ be, but doesn't assert where it _should_ be.

**Review by levithomason — CHANGES_REQUESTED** [review]

File: test/specs/elements/Button/Button-test.js (hunk 2 above)
Comment (layershifter) [reply test/specs/elements/Button/Button-test.js:114]: I've updated tests as you requested :+1:

**Review by levithomason — APPROVED** [review]

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.67.2`.
