### PR TITLE
Fix floated examples

### LINKED ISSUE #55: Floated examples break the docs code layout
This can be easily circumvented if the code snippet were in its own column.  There should also be some more padding between examples.  We should toss that in this fix as well.

image

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #55, also makes a couple aesthetic improvements to the examples section.

### CODE REVIEW

File: docs/app/Components/ComponentDoc/ComponentExample.js [hunk 1]
```diff
@@ -25,13 +25,15 @@ export default class ComponentExample extends Component {
...
   render() {
     let code = (
-      <Highlight className='language-javascript'>
-        {this.fileContents}
-      </Highlight>
+      <Column>
+        <Highlight className='language-javascript'>
+          {this.fileContents}
+        </Highlight>
+      </Column>
```
Comment (levithomason) [inline docs/app/Components/ComponentDoc/ComponentExample.js:32]: Wrapping code in its own column separates it from the float issues.  Also adds some pleasant whitespace.

File: docs/app/index.html [hunk 2]
```diff
@@ -4,7 +4,7 @@
   <title>Stardust Docs</title>
 
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.4/semantic.min.css" />
-  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/styles/androidstudio.min.css">
+  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.8.0/styles/github.min.css">
```
Comment (levithomason) [inline docs/app/index.html:7]: The dark theme was pretty loud on the light doc site, switched it to github theme:

image

File: docs/app/Components/ComponentDoc/ComponentExample.js [hunk 3]
```diff
@@ -25,13 +25,15 @@ export default class ComponentExample extends Component {
...
     );
 
     return (
-      <Grid className='one column'>
+      <Grid className='one column' style={{marginBottom: '4em', marginTop: '4em'}}>
```
Comment (levithomason) [inline docs/app/Components/ComponentDoc/ComponentExample.js:36]: Adds extra whitespace between examples for readability.
