### PR TITLE
fix(TransionablePortal): fix state handling

### LINKED ISSUE #2382: TransitionablePortal: doesn't close on closeOnDocumentClick
hi,
It works with Portal but not with Transitionable..
Note that the Portal controlled demo here https://react.semantic-ui.com/addons/portal doesn't work too.

Version 0.76.0

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2382.

### CODE REVIEW

File: src/addons/TransitionablePortal/TransitionablePortal.js [hunk 1]
```diff
@@ -99,13 +97,8 @@ export default class TransitionablePortal extends Component {
...
   handlePortalClose = () => {
     debug('handlePortalClose()')
-    const { open } = this.props
-    const { portalOpen } = this.state
 
-    // Heads up! We simply call `onClose` when component is controlled with `open` prop.
-    // But, when it's autocontrolled we should change the state to opposite to keep the transition
-    // queue
-    if (_.isNil(open)) this.setState({ portalOpen: !portalOpen })
+    this.setState({ portalOpen: false })
```
Comment (layershifter) [inline src/addons/TransitionablePortal/TransitionablePortal.js:101]: I rethought the state handling there and as I see, it was overcomplicated. I've simplified it and it looks that everything is correct.

File: src/addons/TransitionablePortal/TransitionablePortal.js [hunk 2]
```diff
@@ -99,13 +97,8 @@ export default class TransitionablePortal extends Component {
 
   handlePortalClose = () => {
     debug('handlePortalClose()')
-    const { open } = this.props
-    const { portalOpen } = this.state
 
-    // Heads up! We simply call `onClose` when component is controlled with `open` prop.
```
Comment (layershifter) [inline src/addons/TransitionablePortal/TransitionablePortal.js:105]: Cruft, we don't call `onClose` and it seems that condition below doesn't make sence.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.77.2`
