### PR TITLE
fix(Search): only call onBlur & onFocus event handler once

### LINKED ISSUE #1962: SearchField triggers blur & focus event twice
### Steps
Click in the SearchField to set focus

### Expected Result
The focus event handler is called once.

### Actual Result
The focus event handler is called twice. the same applies to blur event.

### Version
0.71.4

### Testcase
https://codepen.io/anon/pen/rzGzPp?editors=1111

### PR DESCRIPTION
**Pull request by chopstikk**
Fixes #1962 

Search component onBlur and onFocus event handers should not be called twice.

### CODE REVIEW

**Review by layershifter — CHANGES_REQUESTED** [review]
@chopstikk Thanks for PR. However, I think that we should add tests there to omit such cases in future.

Something like:
```js
describe('onFocus', () => {
  it('is called with (e, data)', () => {
    const onFocus = sandbox.spy()
    wrapperMount(<Search onFocus={onFocus} />)
    
    wrapper.simulate('focus')

    onFocus.should.have.been.calledOnce()
    onFocus.should.have.been.calledWithMatch({ }, { options })
  })
})
```

File: test/specs/modules/Search/Search-test.js [hunk 1]
```diff
@@ -525,6 +525,28 @@ describe('Search', () => {
     })
   })
 
+  describe('onBlur', () => {
+    it('is called with (event) on search input blur', () => {
+      const spy = sandbox.spy()
```
Comment (layershifter) [inline test/specs/modules/Search/Search-test.js]: Please name `spy` as event handler, i.e. `onBlur`.

File: test/specs/modules/Search/Search-test.js [hunk 2]
```diff
@@ -525,6 +525,28 @@ describe('Search', () => {
...
+      wrapperMount(<Search onBlur={spy} />)
+        .simulate('blur', nativeEvent)
+
+      spy.should.have.been.calledOnce()
+      spy.should.have.been.calledWithMatch(nativeEvent)
```
Comment (layershifter) [inline test/specs/modules/Search/Search-test.js]: Let's also check that second argument provides a valid props:

```diff
-wrapperMount(<Search onBlur={spy} />)
+wrapperMount(<Search onBlur={spy} results={options} />)

-spy.should.have.been.calledWithMatch(nativeEvent)
+spy.should.have.been.calledWithMatch(nativeEvent, { onBlur, results: options })
```

File: test/specs/modules/Search/Search-test.js [hunk 3]
```diff
@@ -525,6 +525,28 @@ describe('Search', () => {
     })
   })
 
+  describe('onBlur', () => {
+    it('is called with (event) on search input blur', () => {
```
Comment (layershifter) [inline test/specs/modules/Search/Search-test.js]: Let's also correct a title `is called with (e, data) on...`

**Review by layershifter — CHANGES_REQUESTED** [review]

**Review by layershifter — APPROVED** [review]

**Comment by levithomason** [comment]
I love you two, thanks! 😄

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.5`
