### PR TITLE
fix(Comment): spread image props on CommentAvatar

### LINKED ISSUE #3250: Comment: CommentAvatar has no alt field
### Problem description

CommentAvatar has not way to setup any `alt` field, much important for any accessibility concerns

### Proposed solution

Provide a way to have an `alt`. Cheers!

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #3250.

---

### Before
```html
<div alt='Example' class='avatar'>
  <img src='matt.jpg' />
</div>
```

### After

```html
<div class='avatar'>
  <img alt='Example' src='matt.jpg' />
</div>
```

### CODE REVIEW

File: src/elements/Image/Image.js [hunk 1]
```diff
@@ -20,8 +21,6 @@ import Dimmer from '../../modules/Dimmer'
 import Label from '../Label/Label'
 import ImageGroup from './ImageGroup'
 
-const imageProps = ['alt', 'height', 'src', 'srcSet', 'width']
```
Comment (layershifter) [inline src/elements/Image/Image.js:23]: Moved to `lib` because is reusable.
