### PR TITLE
fix(Dropdown): clear searchQuery on item selection by mouse click

### LINKED ISSUE #3306: Dropdown: multiple does not clear on mouse click
### Steps
Use a Multiple-search dorpdown, such as the one in this example
https://react.semantic-ui.com/modules/dropdown/#types-multiple-search-selection
Type "A". A few values will be offered
With your **mouse**, select any of the values
### Expected Result
The "a" searchQuery is cleared

### Actual Result
The "a" searchQuery remains

### Version
0.83.0

### Note
If you use keyboard only to select a value from the list, then the proper behavior occurs. The issue is only when using the mouse

### PR DESCRIPTION
**Pull request by kohakukun**
- Remove check to have consistent behavior with `selectItemOnEnter`

Fixes #3306.

### CODE REVIEW

File: src/modules/Dropdown/Dropdown.js [hunk 1]
```diff
@@ -729,8 +729,7 @@ export default class Dropdown extends Component {
     this.setValue(newValue)
     this.setSelectedIndex(value)
 
-    const optionSize = _.size(this.getMenuOptions())
-    if (!multiple || isAdditionItem || optionSize === 1) this.clearSearchQuery()
+    this.clearSearchQuery()
```
Comment (layershifter) [inline src/modules/Dropdown/Dropdown.js:732]: This change is absolutely valid, we did this in #2162 and even had an comment about this https://github.com/Semantic-Org/Semantic-UI-React/pull/2162#issuecomment-355130565.

See our decision https://github.com/Semantic-Org/Semantic-UI-React/pull/2162#issuecomment-334096165. I checked examples manually, LGTM.

**Comment by layershifter** [comment]
@kohakukun thanks for the investigation 👍
