### PR TITLE
test(Examples): assert no console errors

### LINKED ISSUE #599: docs(Example): Fix warnings
We have warnings in docs and test, they throw warnings in prop validation.
### Menu
- [ ] Complete

> Warning: Failed prop type: Invalid prop `link` of type `string` supplied to `Icon`, expected `boolean`.
>    in Icon (created by Input)
>    in Input (created by TabularOnTop)
>    in div (created by MenuItem)
>    in MenuItem (created by TabularOnTop)
>    in div (created by MenuMenu)
>    in MenuMenu (created by TabularOnTop)
>    in div (created by Menu)
>    in Menu (created by TabularOnTop)
>    in div (created by TabularOnTop)
>    in TabularOnTop
### Table
- [ ] Complete

> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Table`. See https://fb.me/react-warning-keys for more information.
>    in TableRow (created by Table)
>    in Table (created by TableWarningShorthand)
>    in TableWarningShorthand
> 
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TableRow`. See https://fb.me/react-warning-keys for more information.
>    in TableCell (created by TableRow)
>    in TableRow (created by Table)
>    in thead (created by TableHeader)
>    in TableHeader (created by Table)
>    in table (created by Table)
>    in Table (created by TableWarningShorthand)
>    in TableWarningShorthand
### Feed
- [ ] Complete

> Warning: Failed prop type: Prop `children` in `FeedContent` conflicts with props: `date`. They cannot be defined together, choose one or the other.
>    in FeedContent (created by ContentBlock)
>    in ContentBlock
> 
> Warning: Failed prop type: Prop `date` in `FeedContent` conflicts with props: `children`. They cannot be defined together, choose one or the other.
>    in FeedContent (created by ContentBlock)
>    in ContentBlock
### Dropdown
- [ ] Complete

> Warning: Failed prop type: `children` prop in `Dropdown` requires props: `text`.
>    in Dropdown (created by DropdownTriggerExample)
>    in DropdownTriggerExample
> 
> Warning: Failed prop type: `options` prop in `Dropdown` requires props: `selection`.
>    in Dropdown (created by DropdownHeaderExample)
>    in DropdownHeaderExample
### Portal
- [ ] Complete

> ```
> ✔ should call props.onUnmount() only once when portal closes and then is unmounted
> ```
> 
> ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactClass component.'
>      ✔ should call props.onUnmount() only once when directly unmounting
> ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactClass component.'
>      ✔ should not call this.setState() if portal is unmounted
> ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ReactClass component.'
### Select
- [ ] Complete

> ✔ is exported at the top level
> ERROR: 'Warning: Failed prop type: `selection` prop in `Dropdown` requires props: `options`.
>     in Dropdown'
### Grid
- [x] Complete

> ✔ adds numberToWord value to className
> ERROR: 'Warning: Failed prop type: Invalid prop `columns` of value `equal` supplied to `GridRow`, expected one of ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16",1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,"one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen"].
>     in GridRow'
### Menu
- [ ] Complete

> ✔ renders children
> ERROR: 'Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (7 has parents 0 and 6).
### Table
- [ ] Complete

> shorthand
>      ✔ renders empty tbody with no shorthand
> ERROR: 'Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Table`. See https://fb.me/react-warning-keys for more information.
>    in TableRow (created by Table)
>    in Table (created by Unknown)
>    in Unknown'
> ERROR: 'Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TableRow`. See https://fb.me/react-warning-keys for more information.
>    in TableCell (created by TableRow)
>    in TableRow (created by Table)
>    in thead (created by TableHeader)
>    in TableHeader (created by Table)
>    in table (created by Table)
>    in Table (created by Unknown)
>    in Unknown'
### TableRow
- [ ] Complete

> ```
>  ✔ does not add prop value to className
> ```
> 
> ERROR: 'Warning: validateDOMNesting(...): <tr> cannot appear as a child of <div>. See div > (unknown) > TableRow > tr.'
### Button
- [ ] Complete

> ✔ adds className icon
> ERROR: 'Warning: Failed prop type: Given props { icon: "user" }: Prop `children` in `Button` conflicts with props: `icon`. They cannot be defined together, choose one or the other.
>     in Button'
### Label
- [ ] Complete

> ✔ is not included in className when not defined
> ERROR: 'Warning: Failed prop type: `empty` prop in `Label` requires props: `circular`.
>     in Label'
### Loader
- [x] Complete

> ✔ is not included in className when not defined
> ERROR: 'Warning: Failed prop type: Invalid prop `text` supplied to `Loader`, expected a ReactNode.
>     in Loader'
### Accordion
- [ ] Complete

> onTitleClick
>      ✔ is called with (event, index)
> ERROR: 'Warning: Failed prop type: Prop `children` in `Accordion` conflicts with props: `panels`. They cannot be defined together, choose one or the other.
>     in Accordion'
> ERROR: 'Warning: Failed prop type: Prop `panels` in `Accordion` conflicts with props: `children`. They cannot be defined together, choose one or the other.
>     in Accordion'
### Dropdown
- [ ] Complete

>    ✔ is tabbable
> ERROR: 'Warning: Failed prop type: `options` prop in `Dropdown` requires props: `selection`.
>     in Dropdown'
> 
> trigger
>      ✔ displays the trigger
> ERROR: 'Warning: Failed prop type: Prop `trigger` in `Dropdown` conflicts with props: `text`. They cannot be defined together, choose one or the other.
>     in Dropdown'
> 
> ```
>   ✔ passes the name prop to the hidden select
> ```
> 
> ERROR: 'Warning: Failed prop type: Invalid prop `value` supplied to `Dropdown`.
>     in Dropdown'
### Modal
- [x] Complete

> ```
>     ✔ adds an inverted dimmer to the body
> ```
> 
> ERROR: 'Warning: Unknown props `onClose`, `defaultOpen` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by Modal)'
> 
> ```
>   ✔ is not called when the open prop changes to false
> ```
> 
> ERROR: 'Warning: Unknown props `closeOnEscape`, `closeOnDocumentClick` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
>     in div (created by Modal)'
>    with configurable close behaviours, onClose
### ~~Search~~ Input

Note: This warning is actually coming from the `Input` not setting `onChange` on a controlled input.
- [x] Complete

> ✔ closes the menu
> ERROR: 'Warning: Failed form propType: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `Input`.'

### LINKED ISSUE #604: RFC: Open questions around "Collection Shorthand"
See https://github.com/TechnologyAdvice/stardust/pull/567#discussion_r81444584 for a more detailed description of what I'm calling "Collection Shorthand".

---

I've been thinking about collection shorthand a little bit and have some open questions that I wanted to bring up so we can start figuring it out.
### ChildKey

When rendering the `items` it's necessary to generate a unique key for each item unless one is passed. In some cases it may be possible to do this given the props (see the rendering of each `MenuItem` [here](https://github.com/TechnologyAdvice/stardust/blob/master/src/collections/Menu/Menu.js#L166). However, there are issues even with this type of approach
- If the items are string/props shorthand, generally we'll be able to imply a key from those props. However, if the items are elements with only children, this wouldn't work (e.g. in the `MenuItem` case the content/name props would be blank).
- Certain types of data may not even have uniqueness amongst content. `TableRow > TableCell` comes to mind. Imagine a row where each cell is the string "n/a" - we'd be unable to generate a key just from the props.

Should we do any of the following:
- Fallback to index-based keys in cases where we can't guarantee uniqueness. This is an anti-pattern but it would work. Perhaps we do this and display a warning in dev like "no `key` or `childKey` was passed so we're falling back to index-based keys, which can yield unreliable results. You should specify keys yourself to guarantee uniqueness".
- Don't set a default childKey unless we're certain we guarantee uniqueness and just have the user see the `Warning: Each child in an array or iterator should have a unique "key" prop`.

When you're missing keys, React needs to re-render the whole collection because it can't be sure. When you generate duplicate keys for different elements React squashes the duplicates and only renders one. So getting it wrong is much worse than just not doing anything.
### Interacting with child props

In some components, it's necessary to be able to use the props for each item created by the shorthand. For example, there's an open issue to allow specifying string elements for `Dropdown` options (#470). In this case, I think it makes sense to make to use shorthand. However, we need to do things like filtering/searching, which rely on turning a literal into a props object or being able to use the props of a passed React element.

I'm thinking we can do something like this:
- whenever props change (e.g. componentWillMount, componentWillReceiveProps), if the `items` have changed we run something like (e.g. for `Dropdown`):

``` js
this.setState({ items: _.map(this.props.items, (item, index) => DropdownItem.create(item, defaultProps) })
```
- now whenever we do anything with the items, they will be always be fully "hydrated" react elements so we can interact with them in a consistent way (e.g. `item.props.value`) instead of needing to do something like `_.isObject(item) ? item.value : item`.

---

There may be some other issues so feel free to add them here for discussion.

Thoughts?

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #604 
Fixes #599 

This PR adds a test that renders all doc site examples and asserts that no console errors were logged.  I'll fix the errors as well before merging.  I may also extend this to render all doc site routes instead, that way every page is covered and we know there are no console errors in the docs.

```
FAILED TESTS:
  examples
    ✖ render without errors
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Example File: ./collections/Menu/Types/Attached.js
      Console Error: Warning: Failed prop type: `children` prop in `Dropdown` requires props: `text`.
          in Dropdown

      Example File: ./elements/Input/Variations/InputActionDropdown.js
      Console Error: Warning: Failed prop type: `options` prop in `Dropdown` requires props: `selection`.
          in Dropdown

      Example File: ./views/Card/Content/ContentBlock.js
      Console Error: Warning: Failed prop type: Prop `date` in `FeedContent` conflicts with props: `children`. They cannot be defined together, choose one or the other.
          in FeedContent

      : expected [ Array(3) ] to be empty

      Stack:
      test/specs/docs/examples-test.js:27:0
```

### CODE REVIEW

**Comment by jeffcarbs** [comment]
This is great!

While writing examples for `List` shorthand I discovered a bug in how the shorthand was being rendered. Got me thinking - could we automate tests for full markup and shorthand to ensure they produce the same html? This would expose errors in our use of the shorthand or errors within the components themselves - both things we should definitely fix! For example:

``` js
exampleContext.keys().forEach(path) => {
  if (!path.match(/Shorthand$/)) return

  // Makes use of the naming convention of examples
  // Full example: ListExampleBasic
  // Shorthand example: ListExampleBasicShorthand
  const fullExamplePath = path.replace(/Shorthand$/, '')

  const FullExample = createElement(exampleContext(fullExamplePath).default)
  const ShorthandExample = createElement(exampleContext(path).default)

  render(ShorthandExample).should.equal(render(FullExample))
});
```

**Comment by levithomason** [comment]
That sounds pretty sane.  I think we'd need to call [`html()`](http://airbnb.io/enzyme/docs/api/ShallowWrapper/html.html) on the wrapper to compare the html strings, but the point still stands.

I also added `Foo.create()` common tests in https://github.com/Semantic-Org/Semantic-UI-React/pull/644.  The Label create method returned undefined since it was passing `Label` inside of its own class.  The common tests `implementsCreateMethod` just asserts it exists and creates elements for every supported shorthand value.

**Comment by levithomason** [comment]
I updated the test to `mount()` each example, which revealed far more errors.  I've fixed them all except for those with `key` errors.  We need to solve how factories will generate keys, or require the user to pass a `key`, in order to solve this.

Will pick this up later.

```
FAILED TESTS:
  examples
    ✖ renders without errors: ./collections/Table/States/TableWarningShorthand.js
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Console error: Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Table`. See https://fb.me/react-warning-keys for more information.
          in TableRow (created by Table)
          in Table (created by Unknown)
          in Unknown (created by Unknown)
          in Unknown,Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TableRow`. See https://fb.me/react-warning-keys for more information.
          in TableCell (created by TableRow)
          in TableRow (created by Table)
          in thead (created by TableHeader)
          in TableHeader (created by Table)
          in table (created by Table)
          in Table (created by Unknown)
          in Unknown (created by Unknown)
          in Unknown: expected error to not have been called

      Stack:
      test/specs/docs/examples-test.js:21:0

    ✖ renders without errors: ./elements/List/Types/ListExampleBasicShorthand.js
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Console error: Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `List`. See https://fb.me/react-warning-keys for more information.
          in ListItem (created by List)
          in List (created by Unknown)
          in Unknown (created by Unknown)
          in Unknown: expected error to not have been called

      Stack:
      test/specs/docs/examples-test.js:21:0
```

**Comment by levithomason** [comment]
I've pushed some work in progress for creating `key` props for children.  I think we should consider a `createCollection` method.  This way, we know when to create keys.

The `create` method has no way of telling if it is being called due to mapping over a shorthand collection.  Therefore, it has no way of knowing whether or not it should generate a key if none were provided.

If we allow a `createCollection` method, then we can reliably attempt to generate keys and also warn users in development mode if we so choose.  Currently, I'm experimenting with generating a hash code key based on a shallow stringified final props object.  So it's as unique as the full shallow prop signature.  This is only if there were no `key` nor `childKey` provided.  If we only do this when creating a collection (ie `createCollection`) then I think this could be the way to go.

**Comment by levithomason** [comment]
I've split `createShorthandItem` and `createShorthandCollection`.  The latter handles retrieving child keys or generating them.

I just need to finish updating the TableRow.create to utilize the TableCell factory.  It seems collection factories should be responsible for passing the item factory that handles their array values.  Or, use it in the map value to props method.

File: src/collections/Table/Table.js [hunk 1]
```diff
@@ -84,7 +84,7 @@ function Table(props) {
     <ElementType {...rest} className={classes}>
       {headerRow && <TableHeader>{TableRow.create(headerRow, { cellAs: 'th' })}</TableHeader>}
       <TableBody>
-        {renderBodyRow && _.map(tableData, (data, index) => TableRow.create(renderBodyRow(data, index)))}
+        {renderBodyRow && TableRow.create(_.map(tableData, (data, index) => renderBodyRow(data, index)))}
```
Comment (jeffcarbs) [inline src/collections/Table/Table.js]: I think this change is incorrect. This should map over each item in the `tableData` array and create a `TableRow` from each one. This change would map over each item in the `tableData` array and create one giant `TableRow`.

**Comment by levithomason** [comment]
Interestingly in React v15.4 there are no longer warnings for missing keys nor duplicate keys.  It still appears missing or duplicate keys results in overridden child nodes when rendered to the DOM.

I believe I solved all the remaining issues.  I'll come back and clean up and confirm this when I get time.

**Comment by levithomason** [comment]
Haha, there are no warnings because the docs started using React min via CDN...

File: docs/app/Examples/collections/Menu/Types/MenuExampleAttached.js [hunk 2]
```diff
@@ -10,7 +10,7 @@ const MenuExampleAttached = () => {
         <Dropdown as={Menu.Item} icon='wrench' simple>
           <Dropdown.Menu>
             <Dropdown.Item>
-              <Icon name='dropdown icon' />
+              <Icon name='dropdown' />
```
Comment (levithomason) [inline docs/app/Examples/collections/Menu/Types/MenuExampleAttached.js:13]: You'll see several fixes to the docs like this one.

File: docs/app/Examples/elements/List/Content/ListExampleDescription.js [hunk 3]
```diff
@@ -4,14 +4,14 @@ import { List } from 'semantic-ui-react'
 const ListExampleDescription = () => (
   <List>
     <List.Item>
-      <List.Icon name='map marker' />
+      <List.Icon name='marker' />
```
Comment (levithomason) [inline docs/app/Examples/elements/List/Content/ListExampleDescription.js:7]: This was wrong in core docs as well.  There is on a `map` or `marker` icon, not a `map marker`.  The prop type checker is sooo helpful for these :D 

image

File: docs/app/utils.js [hunk 4]
```diff
@@ -18,7 +18,7 @@ export const parentComponents = _.flow(
 /**
  * Get the Webpack Context for all doc site examples.
  */
-export const exampleContext = require.context('docs/app/Examples/', true, /\.js$/)
+export const exampleContext = require.context('docs/app/Examples/', true, /(\w+Example\w+|index)\.js$/)
```
Comment (levithomason) [inline docs/app/utils.js:21]: This now excludes non-renderable other files, like `common.js`.  It is used in a few places, but only for rendering the example view components themselves.

>P.S.  The `common.js` files actually need to go as we cannot truly import any files into the examples since we're in a browser.  That is for another PR.

File: src/collections/Breadcrumb/BreadcrumbSection.js [hunk 5]
```diff
@@ -93,4 +93,4 @@ export default class BreadcrumbSection extends Component {
   }
 }
 
-BreadcrumbSection.create = createShorthandFactory(BreadcrumbSection, content => ({ content, link: true }))
+BreadcrumbSection.create = createShorthandFactory(BreadcrumbSection, content => ({ content, link: true }), true)
```
Comment (levithomason) [inline src/collections/Breadcrumb/BreadcrumbSection.js:96]: This is how we now flag a factory to `generateKey`.  It will generate a key as a hash of shallow props.

File: src/lib/customPropTypes.js [hunk 6]
```diff
@@ -251,6 +251,7 @@ export const contentShorthand = (...args) => every([
 export const itemShorthand = (...args) => every([
   disallow(['children']),
   PropTypes.oneOfType([
+    PropTypes.array,
```
Comment (levithomason) [inline src/lib/customPropTypes.js:254]: Fixes warnings with `tableFooter`.  This prop is shorthand for a Row but the array literal case is passed to the row cells via `mapValueToProps`.  Since the shorthand item factory supports arrays, the shorthand item type should as well.

File: src/lib/factories.js [hunk 7]
```diff
@@ -2,86 +2,146 @@ import _ from 'lodash'
...
-    newProps.className = cx(defaultProps.className, props.className) // eslint-disable-line react/prop-types
+const getHashCode = function hashCode(str) {
+  const { length } = str
+  if (!str || length === 0) return 0
+  let hash = 0
+  for (let i = 0; i < length; i++) {
+    hash = hash * 31 + str.charCodeAt(i) | 0
   }
+  return hash
+}
```
Comment (levithomason) [inline src/lib/factories.js]: When we generate keys we make a prop string, then we make a hash of that.  The only added benefit of the hash is having very short keys.  The downside is more processing at render time.  We could just leave the shallow stringified props as the key.  DOM weight is not an issue here as the key is in memory only.

I'm on the brink of dropping it already, LMK your thoughts.

File: src/lib/getUnhandledProps.js [hunk 8]
```diff
@@ -37,6 +37,7 @@ const getUnhandledProps = (Component, props) => {
   // Return _unhandled_ props
   // ----------------------------------------
   return Object.keys(props).reduce((acc, prop) => {
+    if (prop === 'childKey') return acc
```
Comment (levithomason) [inline src/lib/getUnhandledProps.js:40]: Always "handle" the childKey prop so we don't apply it in factories.

File: test/specs/collections/Table/Table-test.js [hunk 9]
```diff
@@ -59,7 +59,11 @@ describe('Table', () => {
 
     const headerRow = ['Name', 'Status', 'Notes']
 
-    const renderBodyRow = ({ name, status, notes }) => [name || '', status || '', notes || '']
+    const renderBodyRow = ({ name, status, notes }) => [
+      name || { key: 0 },
+      status || { key: 1 },
+      notes || { key: 2 },
```
Comment (levithomason) [inline test/specs/collections/Table/Table-test.js:65]: Since these are cells and in the event that there are multiple missing cells in the `tableData` (which there are) then the cells will all have identical props objects and therefore identical generated keys.

I've instead defaulted to objects with a key defined.

File: test/specs/docs/examples-test.js [hunk 10]
```diff
@@ -0,0 +1,37 @@
...
+    console.log.restore()
+    console.warn.restore()
+    console.error.restore()
+  })
+  exampleContext.keys().forEach(path => {
+    // don't test index files, they repeat errors of individual files
+    if (/index\.js$/.test(path)) return
+    const filename = path.replace(/^.*\/(\w+\.js)$/, '$1')
+
+    it(`${filename} renders without console messages`, () => {
```
Comment (levithomason) [inline test/specs/docs/examples-test.js:27]: 🎉

**Review by levithomason — COMMENTED** [review]
Woop! I believe this ready to go! I've self-reviewed and add some inline notes.  Would be great to get some eyes on this from one of @jcarbo, @davezuko, or @layershifter.

Thanks much!

**Comment by levithomason** [comment]
🎉 🎉 🎉
