### PR TITLE
fix(ComponentExample): fix href in copy link button

### LINKED ISSUE #2770: Docs - Copy link buttons don't work
## Bug Report
Docs - Copy link buttons don't work
### Steps
When I click on a link button the tooltip says 'Copied link!'

### Expected Result
Link address to be in clipboard

### Actual Result
Clipboard remains the same

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2770.

### CODE REVIEW

File: docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js [hunk 1]
```diff
@@ -109,9 +109,8 @@ class ComponentExample extends Component {
   }
 
   handleDirectLinkClick = () => {
-    const { location } = this.props
     this.setHashAndScroll()
-    copyToClipboard(location.href)
+    copyToClipboard(window.location.href)
```
Comment (layershifter) [inline docs/app/Components/ComponentDoc/ComponentExample/ComponentExample.js:113]: We made push to history in `setHashAndScroll`, so we can simply grab `href` from `window.location`

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.80.1`.
