### PR TITLE
fix(Dropdown): simplify typings validation for renderLabel

### LINKED ISSUE #1568: Dropdown renderLabel expects a ReactElement<any> to be returned
According to the example, renderLabel returns an object, so I'm a little confused as to why the Type definition requires a ReactElement. I can't get the example to compile with TypeScript.

Any ideas?

Version 
0.67.2

```

ERROR in ./src/components/Menu/ComponentGroupMenu/ComponentGroupMenu.tsx
(37,11): error TS2322: Type '(item: DropdownItemProps, index: number, label: LabelProps) => { color: string; content: string; ...' is not assignable to type '((item: DropdownItemProps, index: number, defaultLabelProps: LabelProps) => ReactElement<any>) | ...'.
  Type '(item: DropdownItemProps, index: number, label: LabelProps) => { color: string; content: string; ...' is not assignable to type '(item: DropdownItemProps, index: number, defaultLabelProps: LabelProps) => ReactElement<any>'.
    Type '{ color: string; content: string; icon: string; }' is not assignable to type 'ReactElement<any>'.
      Property 'type' is missing in type '{ color: string; content: string; icon: string; }'.

```

code:

````
public render() {
     const options = [
      { key: 1, text: 'Green', value: ComponentGroup.GREEN },
      { key: 2, text: 'Red', value: ComponentGroup.RED },
      { key: 3, text: 'Blue', value: ComponentGroup.BLUE },
    ]

    const renderLabel = (item: DropdownItemProps, index: number, label: LabelProps) => ({
      color: 'blue',
      content: `Customized label - ${label.text}`,
      icon: 'check',
    });

    return (

        <Dropdown
          compact
          selection
          options={options}
          onChange={this.selectGroup} 
          placeholder='Choose an option'
          renderLabel={renderLabel}
        />
    );
  }`
```

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1568.

Simplifies validation for `renderLabel` because it uses `Label`'s factory that can accept element, object or string (ref #1289).

### CODE REVIEW

File: src/modules/Dropdown/Dropdown.d.ts [hunk 1]
```diff
@@ -225,7 +225,7 @@ export interface DropdownProps {
   tabIndex?: number | string;
 
   /** The text displayed in the dropdown, usually for the active item. */
-  text?: string|React.ReactNode;
+  text?: string;
```
Comment (layershifter) [inline src/modules/Dropdown/Dropdown.d.ts:228]: `text` prop can be only string.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.0`.
