### PR TITLE
fix(Layouts): fix behaviour of Sidebar in mobile view

### LINKED ISSUE #2625: Layouts: HomepageLayout in mobile menu automatically toggled when click somewhere
✖ CSS ISSUES → Post on https://github.com/Semantic-Org/Semantic-UI

✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://react.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI-React
      SO - https://stackoverflow.com/questions/tagged/semantic-ui-react?sort=votes

✔ BUGS → This form is required:

### Steps

Chrome Developer Menu => Mobile View => Access below url 
https://react.semantic-ui.com/layouts/homepage

### Expected Result

Menu has to toggled when burger clicked. 

### Actual Result

But, when you click anywhere in page, menu automatically toggled. 

### Version

Latest

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #2625.

### CODE REVIEW

File: docs/app/Layouts/HomepageLayout.js [hunk 1]
```diff
@@ -122,10 +128,10 @@ class MobileContainer extends Component {
             <Menu.Item as='a'>Company</Menu.Item>
             <Menu.Item as='a'>Careers</Menu.Item>
             <Menu.Item as='a'>Log in</Menu.Item>
-            <Menu.Item as='a' primary>Sign Up</Menu.Item>
```
Comment (layershifter) [inline docs/app/Layouts/HomepageLayout.js:125]: Copy-paste, `Menu.Item` can't be `primary`

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.79.0`.
