### PR TITLE
docs(Search): fix examples

### LINKED ISSUE #1846: Search: examples broken
Check your examples
https://react.semantic-ui.com/modules/search

error from console: 

> Failed prop type: Invalid prop `value` of type `object` supplied to `Search`, expected `string`.

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #1846.

I performed breaking changes in #1828, but I forget about update to docs.

### CODE REVIEW

File: docs/app/Examples/modules/Search/Types/SearchExampleCategoryCustom.js [hunk 1]
```diff
@@ -4,8 +4,7 @@ import { Label } from 'semantic-ui-react'
 
 import SearchExampleCategory from './SearchExampleCategory'
 
-const categoryRenderer = ({ name }) =>
-  <Label as={'span'} content={name} />
```
Comment (layershifter) [inline docs/app/Examples/modules/Search/Types/SearchExampleCategoryCustom.js:8]: This should be one line.

File: docs/app/Examples/modules/Search/Types/SearchExampleStandard.js [hunk 2]
```diff
@@ -17,9 +17,9 @@ export default class SearchExampleStandard extends Component {
 
   resetComponent = () => this.setState({ isLoading: false, results: [], value: '' })
 
-  handleResultSelect = (e, result) => this.setState({ value: result.title })
+  handleResultSelect = (e, { result }) => this.setState({ value: result.title })
 
-  handleSearchChange = (e, value) => {
```
Comment (layershifter) [inline docs/app/Examples/modules/Search/Types/SearchExampleStandard.js:22]: Forgotten change.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.71.1`.
