### PR TITLE
fix(Checkbox): focus should be obtained on mouseDown

### LINKED ISSUE #1335: Checkbox: focus not properly activated on click
### Steps
1. Add a checkbox: `<Checkbox label="Label"/>`
2. Click the checkbox or the label.

### Expected Result
The checkbox should get focus. `onFocus` should be triggered.

### Actual Result
On Windows 7 64-bit:
Firefox 51.0.1 (32-bit): The checkbox does not get focus. `onFocus` is not triggered.
Chromium 58.0.3009.0 (64-bit): The checkbox does not get focus. `onFocus` is not triggered.
Internet Explorer 11.0.9600.18537: `onFocus` is triggered (as well as `onBlur`), but the focus is not visible.

In all three browsers the focus works as expected when using the tab key.

[Checkboxes in core Semantic UI](http://semantic-ui.com/modules/checkbox.html) work as expected.

### Version
0.64.8

### Testcase
http://codepen.io/anon/pen/apMgvO

### PR DESCRIPTION
**Pull request by layershifter**
Finally fixes #1335.

~~We added focus capture in #1361, but we added it into the `onMouseDown` handler while it should be inside `onClick` handler.~~

### CODE REVIEW

File: src/modules/Checkbox/Checkbox.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import cx from 'classnames'
-import _ from 'lodash/fp'
+import _ from 'lodash'
```
Comment (layershifter) [inline src/modules/Checkbox/Checkbox.js:2]: @levithomason I removed usage of `lodash/fp` because I don't understand how I can make this in FP style:

```js
_.invoke(this.props, 'onMouseDown', e, { ...this.props, checked: !!checked, indeterminate: !!indeterminate })
```

Comment (levithomason) [reply src/modules/Checkbox/Checkbox.js:2]: No worries, this works 👍

**Comment by levithomason** [comment]
## Order of events

The order of events as fired by the browser are: `mouseDown`, `focus`, `mouseUp`, `click`.  I've added the following handlers to this comment textarea on github and here's the result:

```js
new_comment_field.addEventListener('click', () => console.log('click'))
new_comment_field.addEventListener('mousedown', () => console.log('mousedown'))
new_comment_field.addEventListener('mouseup', () => console.log('mouseup'))
new_comment_field.addEventListener('focus', () => console.log('focus'))
```
A click, long press, and release logs this:



## onBlur

That said, our bug is that the `onBlur` callback is called immediately _after_ the `onFocus` callback.  So, the reported codepen ends up setting state `true` in `onFocus` and setting it back to `false` in `onBlur`.  The `onFocus` event is working correctly, it is just that there is an extra `onBlur` event firing first.  You can see this easily by removing the `onBlur` handler and the state is updated correctly via `onFocus`.

This extra blur event is a side effect of calling `inputRef.focus()` in the `onMouseDown` handler for what is actually the `label` element. We can circumvent this issue by simply preventing the default event in `onMouseDown`.  That way, we call `onMouseDown` then `inputRef.focus()` without causing the extra unnecessary blur:

**Update to this PR**
```diff
// handleClick() {
// ..snip
    _.invoke(this.props, 'onChange', e, { ...this.props, checked: !checked, indeterminate: false })

    this.trySetState({ checked: !checked, indeterminate: false })
-   _.invoke(this.inputRef, 'focus')
  }

  handleMouseDown = e => {
    debug('handleMouseDown()')
    const { checked, indeterminate } = this.state

    _.invoke(this.props, 'onMouseDown', e, { ...this.props, checked: !!checked, indeterminate: !!indeterminate })
+   _.invoke(this.inputRef, 'focus')
+   e.preventDefault()
  }
```

## The test

This results in the correct behavior as well as the correct order of events fired:



***

Give that a try and let me know your thoughts.

**Comment by layershifter** [comment]
@levithomason Thanks for a detailed reply. You're right there, seems that SUI implements focus incorrectly, it triggers `focus` after click. The behaviour that you described is more native. I will perform changes in this PR.

**Comment by levithomason** [comment]
Thanks for the confirmation and second round.

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.69.0`
