### PR TITLE
Fix test warnings

### LINKED ISSUE #60: Cleanup redundancy in tests
There is a lot of redundancy in tests.  Mostly, `findFoo()` calls serve both query and assertion purposes. These are equivalent:

``` jsx
let gridClassName = render(<Grid />).findClass('sd-grid').props.className;
gridClassName.should.contain('sd-grid');
```

``` jsx
render(<Grid />).findClass('sd-grid');
```

Update all tests to remove their redundant assertions.

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #60 #95 
- Make tests pass without warnings (React 0.14 compliant)
- Simplify and cleanup test code
- Remove component tests for which there is a conformance test
  
  > inheriting classes, spreading props, etc

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -6,7 +6,7 @@
 _builds/
 _projects/
 _steps/
-npm-debug.log
+npm-debug.log*
```
Comment (levithomason) [inline .gitignore:9]: some debug logs have a hash at the end: `npm-debug.log1284987-12asdf1-1234a`

File: test/specs/collections/Form/Field-test.js [hunk 2]
```diff
@@ -7,18 +7,16 @@ describe('Field', () => {
...
     render(<Field label='First Name' />)
       .findTag('label')
-      .props.children.should.equal('First Name');
+      .textContent.should.equal('First Name');
   });
 
   it('renders children', () => {
-    render(<Field label='First Name'>yo child</Field>)
-      .findText('yo child');
+    render(<Field>yo child</Field>).assertText('yo child');
```
Comment (levithomason) [inline test/specs/collections/Form/Field-test.js:14]: Heads up, `findText` is gone.  Instead, `assertText` exists, you will not get the element back, only a bool.

**Comment by athurman** [comment]
looks good! :ocean: :octopus:
