### PR TITLE
docs(mixed): improve perf & bundle size, fix issue with /layouts

### LINKED ISSUE #3633: Website: layouts page layout broken
## Bug Report

When I visit [https://react.semantic-ui.com/](https://react.semantic-ui.com/) and navigate to [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) using the link in the sidemenu, everything is fine.

However, if I visit [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) directly, the layout of the page is broken.

### Steps

Visit [https://react.semantic-ui.com/layouts/](https://react.semantic-ui.com/layouts/) directly in the browser. Tested with Opera and Edge (don't have Chrome installed atm, but Opera is chromium based and should have a similar rendering experience)

### Expected Result
image

### Actual Result
image

### Version
N.A.

### Testcase
N.A.

### LINKED ISSUE #3645: Doc: "Get Started" guide on using custom themes is outdated and misleading
On https://react.semantic-ui.com/usage, under the "Custom Theme" tab of the "Theme" section, the recommendation is

> The Semantic UI package installs a Gulp build tool that will walk you through creating a custom theme within your project. Install this as a dev dependency:
>
>     $ yarn add semantic-ui --dev
> 
> After building a theme with Gulp, include the minified CSS file in your index.js file:
>
>     import '../semantic/dist/semantic.min.css
>
> Detailed documentation on Semantic UI theming is provided here and in our Theming guide.

Unfortunately, `semantic-ui` is stuck on Gulp 3 and incompatible with Node 12 (https://github.com/Semantic-Org/Semantic-UI/issues/6818). This sent me on a wild goose chase that ended nowhere; then I checked the Theming guide which is based on `semantic-ui-less` and works without a problem.

So, the `semantic-ui` mention is misleading and kinda does this project a disservice. Would you please update that section? Thanks.

### LINKED ISSUE #3659: Doc - Theme - Theming with Create React App - Scaffold custom styles
## Bug Report

The Theme doc for theming with Create React App has a step where you copy some theme files but running the following command will copy all the files without the theme folder structure and in a flat way.
`
yarn cpy node_modules/semantic-ui-less/_site/**/* src/semantic-ui/site
`
### Steps
Follow the tutorial and execute the script

### Expected Result
It will copy all the theme files with the right theme folder structure

### Actual Result
After the running the script you'll see a flat file structure without the theme folders

### Version
Current site version

### PR DESCRIPTION
**Pull request by layershifter**
Fixes #3633.

Previously we had broken match on `/layouts`, see https://github.com/Semantic-Org/Semantic-UI-React/pull/3652#discussion_r291841872.

---

Fixes #3645.

Mention about `semantic-ui` package was removed, we have dedicated page with instructions for theming.

---

Fixes #3659.

Instructions were updated, also added NPM to commands.

---

Polishes a little bit shorthand docs.

### CODE REVIEW

File: docs/src/App.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ const App = ({ componentMenu, versions }) => (
            * We can't place <Sidebar /> inside of <Routes /> because it will be remounted on page
            * switch. We also don't want to show <Sidebar /> for layouts pages and maximized pages.
            */}
-          <Route path='/layouts/*' component={null} />
+          <Route exact path='/layouts/:name' component={null} />
```
Comment (layershifter) [inline docs/src/App.js:20]: Because `/layouts` because same the same prefix, we had match there and sidebar was hidden 💥
