### PR TITLE
fix(Accordion): Fixed incorrect defaultActiveIndex check

### LINKED ISSUE #772: Accordion does not work properly when defaultActiveIndex is 0
set defaultIndex to 0, the panel will not unfold. but rest of the index, it works properly.

My code here (v0.58.0)

```
import React, { Component } from 'react'
import { Accordion } from 'semantic-ui-react'
import faker from 'faker'
import _ from 'lodash'

const panels = _.times(3, () => ({
  title: faker.lorem.sentence(),
  content: faker.lorem.paragraphs(),
}))

export default class AccordionPanelsPropExample extends Component {
  render() {
    return (
      // at index 0 not working, but rest index working fine. 1 or 2
      <Accordion defaultActiveIndex={0} panels={panels} />
    )
  }
}
```

### PR DESCRIPTION
**Pull request by Arthelon**
Fixes #772

This PR fixes the incorrect check of the props defaultActiveIndex in the componentWillMount hook. Instead of using the ! operator, which evaluates falsy values like 0 to true, the new condition checks for an undeclared variable or the number -1.

### CODE REVIEW

**Comment by Arthelon** [comment]
@levithomason Sorry for the trouble. Fixed.

File: src/modules/Accordion/Accordion.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ export default class Accordion extends Component {
     // Otherwise, on first render we're allowed to set state for a prop that might have a default.
     // The default prop should always win on first render.
     // This default check should then be removed.
-    if (!this.props.defaultActiveIndex) {
+    if (typeof this.props.defaultActiveIndex === 'undefined' || this.props.defaultActiveIndex === -1) {
```
Comment (levithomason) [inline src/modules/Accordion/Accordion.js]: I believe this should only have the `undefined` check, true?  We only want to set the activeIndex if it was not already set.

If the prop were already set to `-1` then the auto controlled state will already be `-1` and we don't want to try to set it again.

LMK your thoughts on this.

Comment (Arthelon) [inline src/modules/Accordion/Accordion.js]: @levithomason the typeof check for any undeclared or undefined variable will be "undefined"

Comment (levithomason) [reply src/modules/Accordion/Accordion.js]: So, I am proposing that I _believe_ this is the correct logic:

```diff
-if (typeof this.props.defaultActiveIndex === 'undefined' || this.props.defaultActiveIndex === -1) {
+if (typeof this.props.defaultActiveIndex === 'undefined') {
  // ...
}
```

Comment (Arthelon) [reply src/modules/Accordion/Accordion.js]: Yes, that would make more sense. Thanks for the catch!

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.61.5`.
