### PR TITLE
fix(Form): pass shorthand ids to the label's htmlFor prop

### LINKED ISSUE #980: Label click for input element (accessibility)
I've noticed that the input form element label is not clickable. This means that its not possible to click on the label to focus on the input element. Is this something that was omitted or something I missed? 

I know the current workaround is to provide my own htmlFor element like this but I would prefer that the Form.Input would work like this out of the box. 

```javascript
<Form.Field>
  <label htmlFor="password">Password</label>
  <input
    id="password"
    name="password"
    type="password"
  />
</Form.Field>
```

### PR DESCRIPTION
**Pull request by pedrocostadev**
Added new prop id to Form.Input's component and use it also for htmlFor label. Updated the docs example to show results.
This is my first step here so, if you need something more to merge, just tell me please :-)

Resolve #980

### CODE REVIEW

File: docs/app/Examples/collections/Form/Shorthand/FormExampleSubComponentControl.js [hunk 1]
```diff
@@ -16,8 +16,8 @@ class FormExampleSubComponentControl extends Component {
     return (
       <Form>
         <Form.Group widths='equal'>
-          <Form.Input label='First name' placeholder='First name' />
-          <Form.Input label='Last name' placeholder='Last name' />
+          <Form.Input id='form-input-shorthand-first-name' label='First name' placeholder='First name' />
+          <Form.Input id='form-input-shorthand-last-name' label='Last name' placeholder='Last name' />
```
Comment (levithomason) [inline docs/app/Examples/collections/Form/Shorthand/FormExampleSubComponentControl.js]: I'd like to have two dedicated examples for this in the docs under one heading.  One example showing the usage with `Form.Field` and another showing usage with `Form` shorthand subcomponents.  

First, create two example files in `docs/app/Examples/collections/Form/Shorthand`, probably:
1. `FormExampleFieldControlId.js` showing `Form.Field` use with the shorthand `control` prop.
2. `FormExampleSubcomponentId.js` showing usage of one or more `Form` subcomponents, i.e. `Form.Input`.

Then, add these files to the `index.js` file in the same directory.  You link examples with the `ComponentExample` component, you'll see several in the `index.js` file.  In order to get two examples to show under one title, only add a `title` to the first example but `descriptions` to both:

```jsx
<ComponentExample
  title='Accessible lables'
  description='Adding an id to a shorthand Form.Field adds a matching htmlFor prop to the label.'
  examplePath='collections/Form/Shorthand/FormExampleFieldControlId'
/>
<ComponentExample
  description='Adding an id to a Form subcomponent adds a matching htmlFor prop to the label.'
  examplePath='collections/Form/Shorthand/FormExampleSubcomponentId'
/>
```

File: src/collections/Form/FormField.js [hunk 2]
```diff
@@ -93,7 +93,7 @@ function FormField(props) {
 
   return (
     <ElementType className={classes}>
-      {createHTMLLabel(label)}
+      {createHTMLLabel(label, { htmlFor: controlProps && controlProps.id })}
```
Comment (levithomason) [inline src/collections/Form/FormField.js]: We'll need a test that asserts the `htmlFor` prop is added when an `id` is passed to `FormField`.  You can find tests in `test/specs/collections/Form/FormField-test.js`.

Let's also add this test to each subcomponent usage (`Form.Input`, etc).  These tests would go in `test/specs/collections/Form/Form-test.js`.

Because this test will be repeated several times, the test itself should be added only once to `commonTests.js`.  You'll see several examples of how to write a common test there.  Just add it to the bottom.  You'll see several examples of how to use a common test in the Form tests I've noted above.

**Review by levithomason — CHANGES_REQUESTED** [review]
Docs look great, thanks!  I've left a couple comments.

**Comment by levithomason** [comment]
I've noticed a couple typos and mixed up references in the Form docs, I'll be pushing those fixes to this branch as well as they are pretty minor.

File: src/lib/htmlInputPropsUtils.js [hunk 3]
```diff
@@ -6,7 +6,7 @@ export const htmlInputAttrs = [
 
   // LIMITED HTML PROPS
   'autoCapitalize', 'autoComplete', 'autoFocus', 'checked', 'form', 'max', 'maxLength', 'min', 'multiple',
-  'name', 'pattern', 'placeholder', 'readOnly', 'required', 'step', 'type', 'value',
+  'name', 'pattern', 'placeholder', 'readOnly', 'required', 'step', 'type', 'value', 'id',
```
Comment (layershifter) [inline src/lib/htmlInputPropsUtils.js]: Please sort props in alphabetical order.

**Review by layershifter — CHANGES_REQUESTED** [review]

**Comment by pedrocostadev** [comment]
Ok guys, I will do that.

**Comment by levithomason** [comment]
Given the number of changed lines and the lack of visible characters changed, I'm betting your IDE is changing the line endings of each file edited.  Are you on Windows by chance?

**Comment by pedrocostadev** [comment]
Usually in Mac but sometimes in Windows. The commit changed more files that suppose?  I check the files when I push and seems all ok.

**Comment by levithomason** [comment]
The files are OK, it is the number of changed lines:

image


And the nature of the changes.  No visible characters have changed, it seems it is likely the line endings:

image

Could you confirm your config is in alignment with these instructions and run the commands from here: https://help.github.com/articles/dealing-with-line-endings?  Let's see if it is indeed the line endings.

**Comment by pedrocostadev** [comment]
It's not the line endings. I checked in the instructions. And now? I need to do something more to the pull request be accepted?

File: docs/app/Examples/collections/Form/Shorthand/FormExampleSubcomponentControl.js [hunk 4]
```diff
@@ -16,8 +16,8 @@ class FormExampleSubComponentControl extends Component {
     return (
       <Form>
         <Form.Group widths='equal'>
-          <Form.Input label='First name' placeholder='First name' />
-          <Form.Input label='Last name' placeholder='Last name' />
+          <Form.Input id='form-input-shorthand-first-name' label='First name' placeholder='First name' />
```
Comment (levithomason) [inline docs/app/Examples/collections/Form/Shorthand/FormExampleSubcomponentControl.js]: Let's remove these now that we other examples.

File: docs/app/Examples/collections/Form/Shorthand/FormExampleSubcomponentId.js [hunk 5]
```diff
@@ -0,0 +1,19 @@
+import React, { Component } from 'react'
+import { Form, Input } from 'semantic-ui-react'
+
+class FormExampleSubcomponentId extends Component {
+  state = {}
```
Comment (levithomason) [inline docs/app/Examples/collections/Form/Shorthand/FormExampleSubcomponentId.js]: This should be a stateless component:

```jsx
const FormExampleSubcomponentId = () => (
  <Form>
    ...
  </Form>
)
```

File: docs/app/Examples/collections/Form/Shorthand/FormExampleFieldControlId.js [hunk 6]
```diff
@@ -0,0 +1,21 @@
+import React, { Component } from 'react'
+import { Form, Input, TextArea, Button } from 'semantic-ui-react'
+
+class FormExampleFieldControlId extends Component {
+  state = {}
```
Comment (levithomason) [inline docs/app/Examples/collections/Form/Shorthand/FormExampleFieldControlId.js]: This should be a stateless component:

```jsx
const FormExampleFieldControlId = () => (
  <Form>
    ...
  </Form>
)
```

File: test/specs/commonTests/implementsCommonProps.js [hunk 7]
```diff
@@ -276,3 +276,36 @@ export const implementsWidthProp = (Component, widths = SUI.WIDTHS, options = {}
...
+ * @param {String} propKey A props key.
+ * @param {Object} [options={}]
+ * @param {Object} [options.requiredProps={}] Props required to render the component.
+ */
+export const labelImplementsHtmlForProp = (Component, propKey, options = {}) => {
+  const { assertRequired } = helpers('labelImplementsHtmlForProp', Component)
+  const { requiredProps = {} } = options
+  describe(`${propKey} (common)`, () => {
+    assertRequired(Component, 'a `Component`')
+    it(`adds ${requiredProps.control} Id to Label's HtmlFor prop`, () => {
```
Comment (levithomason) [inline test/specs/commonTests/implementsCommonProps.js]: We'll need generalize this test a bit more.  It shouldn't know which component it is testing.  We should remove the `control` awareness.

We will then be able to use it in the other `Form*` component tests:

```jsx
labelImplementsHtmlForProp(FormFieldButton)     // FormFieldButton-test.js
labelImplementsHtmlForProp(FormFieldCheckbox)   // FormFieldCheckbox-test.js
labelImplementsHtmlForProp(FormFieldDropdown)   // FormFieldDropdown-test.js
labelImplementsHtmlForProp(FormFieldGroup)      // FormFieldGroup-test.js
labelImplementsHtmlForProp(FormFieldInput)      // FormFieldInput-test.js
labelImplementsHtmlForProp(FormFieldRadio)      // FormFieldRadio-test.js
labelImplementsHtmlForProp(FormFieldSelect)     // FormFieldSelect-test.js
labelImplementsHtmlForProp(FormFieldTextarea)   // FormFieldTextarea-test.js
```

Suggest we don't take any arguments as this test will require the `id` of the top level component to present no the `label` subcomponent after it is rendered.

**Comment by levithomason** [comment]
I've rebased this to master and fixed conflicts.  I also pushed some line ending fixes, `crlf` => `lf`.  Not sure what happened there.

I left a few final comments that should wrap this one up!

**Comment by pedrocostadev** [comment]
For "Checkbox", "Radio" and "Group" the "htmlFor" is not added, so they have not this new test. To implement this in this components I think we need to do different from what i do to the others.
Do you think this should be done for this PR?

**Comment by pedrocostadev** [comment]
So, any news about this?

**Review by levithomason — APPROVED** [review]
Changes look great, thanks!

**Comment by levithomason** [comment]
I've resolved conflicts and will merge on pass.

**Comment by layershifter** [comment]
@levithomason I wan't push some changes, please wait 5 minutes

File: src/collections/Form/FormField.js [hunk 8]
```diff
@@ -94,7 +94,9 @@ function FormField(props) {
 
   return (
     <ElementType className={classes}>
-      {createHTMLLabel(label, { htmlFor: controlProps && controlProps.id })}
+      {createHTMLLabel(label, { defaultProps: {
+        htmlFor: _.get(controlProps, 'id') },
+      })}
```
Comment (layershifter) [inline src/collections/Form/FormField.js]: Factories where updated earlier

File: test/specs/commonTests/implementsCommonProps.js [hunk 9]
```diff
@@ -277,15 +277,19 @@ export const implementsWidthProp = (Component, widths = SUI.WIDTHS, options = {}
...
-      expect(wrapper).to.have.descendants(`#${idToTest}`)
+      const id = 'id-for-test'
+      const label = 'label-for-test'
+
+      const wrapper = mount(<Component id={id} label={label} />)
       const labelNode = wrapper.find('label')
-      labelNode.should.have.prop('htmlFor', idToTest)
+
+      wrapper.should.to.have.descendants(`#${id}`)
+      labelNode.should.have.prop('htmlFor', id)
```
Comment (layershifter) [inline test/specs/commonTests/implementsCommonProps.js]: Updated to use BDD style

**Review by layershifter — APPROVED** [review]
Looks awesome, @pedrocostadev thanks for PR
We can merge on pass

**Comment by pedrocostadev** [comment]
I'm glad to help. Let's go to another :-)

**Comment by levithomason** [comment]
💥

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.1`.

**Comment by camsjams** [comment]
Thanks all - I am glad this was released!
