### PR TITLE
fix(Dropdown): merge Dropdown.Menu className

### LINKED ISSUE #448: Dropdown: support Menu classname
Dropdown.Menu should support passing className as a prop in the same way as Dropdown.Item does, but currently this seems to be missing.

### PR DESCRIPTION
**Pull request by levithomason**
Fixes #448.

The Dropdown clones a Dropdown.Menu child in order to control the open state of the menu by adding the appropriate classes.  We were replacing classes instead of merging classes.  User's classes on Dropdown.Menu were blown away.

This PR merges the open state classes with the user's classes.  It also adds tests to ensure the className and props are properly merged and spread respectively.

### CODE REVIEW

File: src/modules/Dropdown/Dropdown.js [hunk 1]
```diff
@@ -69,7 +69,10 @@ export default class Dropdown extends Component {
     children: customPropTypes.every([
       customPropTypes.disallow(['options', 'selection']),
       customPropTypes.demand(['text']),
-      React.PropTypes.element,
+      customPropTypes.givenProps(
+        { children: PropTypes.any.isRequired },
+        React.PropTypes.element.isRequired,
+      ),
```
Comment (levithomason) [inline src/modules/Dropdown/Dropdown.js:75]: Make children a required single element if it is defined.

File: src/modules/Dropdown/Dropdown.js [hunk 2]
```diff
@@ -801,7 +804,12 @@ export default class Dropdown extends Component {
     const { menuClasses } = this.state
 
     // single menu child
-    if (children) return cloneElement(children, { className: menuClasses })
+    if (children) {
+      const menuChild = Children.only(children)
+      const className = cx(menuClasses, menuChild.props.className)
+
+      return cloneElement(menuChild, { className })
+    }
```
Comment (levithomason) [inline src/modules/Dropdown/Dropdown.js:812]: Merge child classNames.

**Comment by levithomason** [comment]
Released in `stardust@0.38.1`
