### PR TITLE
fix(Dropdown): fix key handling for options

### LINKED ISSUE #1634: Dropdown: Should work with keys instead of values
The Dropdown component is working with each option's value internally. Whereas using the key, if supplied, would be correct.

### Steps
Throw a set of options into a Dropdown with two identical values.

### Expected Result
Show both options.

### Actual Result
1. Only the first option will be displayed.
2. Additionally a React warning is thrown in console: "Warning: flattenChildren(...): Encountered two children with the same key..."

### Version
0.68.1

### Testcase
http://codepen.io/karlludwigweise/pen/xdRvYL

And yes, this is a very very awkward use-case.

### PR DESCRIPTION
**Pull request by dvdzkwsk**
Fixes #1634

### CODE REVIEW

File: src/modules/Dropdown/Dropdown.js [hunk 1]
```diff
@@ -1058,8 +1058,8 @@ export default class Dropdown extends Component {
     return (
       <select type='hidden' aria-hidden='true' name={name} value={value} multiple={multiple}>
         <option value='' />
-        {_.map(options, option => (
-          <option key={option.value} value={option.value}>{option.text}</option>
+        {_.map(options, (option, i) => (
+          <option key={option.key || option.value} value={option.value}>{option.text}</option>
```
Comment (dvdzkwsk) [inline src/modules/Dropdown/Dropdown.js:1062]: To retain parity with the generated `DropdownItem` this should likely include the `-${index}` suffix when using the value as the key. I originally included that fix in this change, but then redacted it since I'd prefer we stop using indexes in keys and require users to provide their own when values are non-unique.

Comment (levithomason) [reply src/modules/Dropdown/Dropdown.js:1062]: Yep.  In fact, this should use a factory which already requires users to use keys when passing objects or elements.  We use literal values for the key otherwise.

See `factories.js` where we should likely add an HTML factory for `option`:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/factories.js#L125

File: src/modules/Dropdown/Dropdown.js [hunk 2]
```diff
@@ -1152,7 +1152,7 @@ export default class Dropdown extends Component {
 
     return _.map(options, (opt, i) => (
       <DropdownItem
-        key={`${opt.value}-${i}`}
+        key={opt.key || `${opt.value}-${i}`}
```
Comment (levithomason) [inline src/modules/Dropdown/Dropdown.js]: Again here, we should add the `create` method to the DropdownItem.  We have a factory creator for this:

**DropdownItem.js**
```jsx
Dropdown.create = createShorthandFactory(Dropdown, val => ({ text: val, value: val }))
```

Then:
```jsx
_.map(options, opt => Dropdown.create(opt)) // PLUS all the other props here...
```

Tests:
**DropdownItem-test.js**
```jsx
common.implementsCreateMethod(Dropdown)
```

Comment (dvdzkwsk) [reply src/modules/Dropdown/Dropdown.js]: Did not know, will take a look. You mean `DropdownItem.create` though, right?

Comment (levithomason) [reply src/modules/Dropdown/Dropdown.js]: Whoops. Yes, sir.`DropdownItem.create`.

**Review by levithomason — APPROVED** [review]
Looks great, thanks @davezuko

**Comment by levithomason** [comment]
Released in `semantic-ui-react@0.68.4`.
